### ISSUE TITLE
Fix your formatting, dude. / Lös' das Problem mit deiner Formatierung, Junge.

### ISSUE THREAD

**Issue by StuxSoftware** [T0biii/TeamSpeakIp#2]
As the title says... Your code formatting looks horrible. Fix it so we can read it.
Wie der Titel sagt: Lös' das Problem mit deiner Formatierung.

**Comment by T0biii** [comment]
Da es jetzt schon über ein Jahr her ist und ich eh nicht wirklich mehr dran arbeite, mal schauen was ich daraus mache :+1:
