### ISSUE TITLE
Server-Gruppen abgleichen mit Essentials Gruppen

### ISSUE THREAD

**Issue by TomberWolf** [T0biii/TeamSpeakIp#9]
Meinst du, du könntest evtl. eine Funktion einbauen die die Server-Gruppen im TS ausliest und an das Essentials Plugin übergibt?

Beispiel: User1 ist im TS in Server-Gruppe "Neulinge", so soll dieser dann auch in Essentials in die Gruppe "Neulinge".

Das wäre ziemlich genial!

**Comment by T0biii** [comment]
Nur woher soll er wissen wie User1 in Minecraft heißt?
Was vielleicht möglich wäre(Viel Code umgeschreiben) das man im TS³ einem !link <mcnamen> schreibt und er ihn dann in die Gruppe setzt. Kenne mich mit den Essentials Plugin nicht so gut aus.
Würde des aber nicht in dieses Projekt/Plugin einbinden weil es dafür eigentlich vorgesehen ist User zu Synchronisieren.
Aber vielleicht könnte ich es in einer Copy von dem Projekt lösen.
Bräuchte aber dann mehr Infos über ein Permissions Plugin,

**Comment by T0biii** [comment]
Habe es mir überlegt und finde des in das Teamspeak³ Plugin einzubinden wäre zu viel aufwand
Und das Teamspeak3 Plugin war nie dafür vorgesehen Ränge zu Synchronisieren.
Damit Close ich das hier mal.
Bei weitern fragen, einfach an mich wenden.

**Comment by T0biii** [comment]
https://www.spigotmc.org/resources/cloudbot-%C3%97-teamspeak%C2%B3-bungeecord-bukkit.17459/
Vielleicht ist das ungefähr so ein Plugin was du gesucht hast.
Ich bin Momentan an der Entwicklung an einem ähnlichen Bot mit MySQL Support only.
Vielleicht veröffentliche ich den wenn ich mir ganz sicher bin das es keine Großen Bugs drin hat.
Bräuchte dafür aber noch Beta Tester.
Wenn jemand Interesse an dem **Beta** Programm hat einfach unter:
**Cloudbot@T0biii.de** eine E-Mail schreiben
Folgende Punkte **müssen** enthalten sein(Die Werte nach dem Doppelpunkt sind Beispiele)
Name: Tobias
TeamspeakIP + Port: 127.0.0.1:9987
Weißt du was ein QueryLogin ist: ja/nein
Skype/Discord/Twitter: Username
MinecraftServerIP: 127.0.0.1:25565
Sonstiges:

**Comment by TomberWolf** [comment]
Ich melde mich sobald ich zu Hause bin. *thumbsup*

**Comment by T0biii** [comment]
@TomberWolf Ich wollte dich nur kurz Informieren das ich bis heute keine Rückmeldung bekommen habe von dir.

**Comment by TomberWolf** [comment]
Und ich wundere mich schon warum von dir nichts mehr kam.
Ich schicke dir die Infos heute nochmal.

**Comment by T0biii** [comment]
Werde vielleicht heute bzw in der nächsten Zeit eine kleine Seite basteln in der man sich dafür anmelden kann einfach damit ich mal bissel mit php spielen kann also selbst mehr über webseiten dazu lerne :)
Dann braucht man auch keine E-Mail mehr verschicken.
Aber der Cloudbot werde ich erst mals nur für Spigot/Bukkit only anbieten,
Für Bungee habe ich zwar schon ne Version aber des ist dann so ne art Premium Version.

**Comment by T0biii** [comment]
Hier ein kleiner einblick in den Frontend: http://puu.sh/u9lfa/07a5b0068d.jpg 
Backend muss noch erstellt werden dann kann man sich darüber bewerben :)
@TomberWolf ich glaube ich bekomme keine E-Mail von dir. 
Warte einfach doch bitte bis ich die Webseite fertig haben dann kannst du dich darüber Bewerben

**Comment by T0biii** [comment]
Finished!
Du kannst dich nun unter: https://t0biii.de/cloudbot
Bewerben :) Viel Glück.

**Comment by T0biii** [comment]
@TomberWolf Hätte die erste Version fertig.
Hättest du noch Lust sie zu Testen ist jetzt doch eine BungeeCord Version geworden.
Vllt addest du mich in Discord T0biii#0406

**Comment by T0biii** [comment]
Da keine Antwort erfolgte 
Projekt ist somit abgeschlossen.
